INSERT INTO books (editorial,genre,image,name,name_author,synopsis) VALUES
	 ('Editorial EDAF','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717236080/wtrvtcycjnmo7h8qusyu.jpg','El Quijote','Miguel de Cervantes','Una novela clásica sobre las aventuras de Don Quijote y Sancho Panza.'),
	 ('Editorial Sudamericana','Realismo Mágico','http://res.cloudinary.com/du4qwkruj/image/upload/v1717239267/ctxutgiqvapki4mx35uu.jpg','Cien años de soledad','Gabriel García Márquez','Una obra maestra del realismo mágico que narra la historia de la familia Buendía.'),
	 ('Seix Barral','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717242975/scoqfebhu9i6d65evfmb.jpg','Rayuela','Julio Cortázar','Una novela innovadora que desafía las convenciones literarias tradicionales.'),
	 ('Lumen','Fantasía','http://res.cloudinary.com/du4qwkruj/image/upload/v1717242985/rj5wuvb2pc5namegnbjq.jpg','El nombre del viento','Patrick Rothfuss','La fascinante historia de un joven con habilidades extraordinarias en un mundo mágico.'),
	 ('Alfaguara','Drama','http://res.cloudinary.com/du4qwkruj/image/upload/v1717242992/pjhdlp7i5qaqxrgklpyv.jpg','La sombra del viento','Carlos Ruiz Zafón','Un misterio literario que explora la magia de los libros en la Barcelona de posguerra.'),
	 ('Planeta','Ciencia Ficción','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243004/fgjvx90ux80wmfcl4wds.jpg','Dune','Frank Herbert','Una épica de ciencia ficción que narra la lucha por el control del desértico planeta Arrakis.'),
	 ('Minotauro','Fantasía','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243017/uulsh1jdpl5wtq7isb4v.jpg','El Hobbit','J.R.R. Tolkien','Las aventuras de Bilbo Bolsón en su búsqueda del tesoro del dragón Smaug.'),
	 ('Tusquets','Terror','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243024/mnmfv951kd8vot1imomj.jpg','El resplandor','Stephen King','La terrorífica historia de un hotel embrujado y la locura que se apodera de su cuidador.'),
	 ('Anagrama','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243031/pfai0magj5wctlqgaaav.jpg','1984','George Orwell','Una distopía que presenta una sociedad totalitaria y la vigilancia extrema.'),
	 ('Acantilado','Novela Histórica','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243041/fo1ip78bd5cvj8zz4v8d.jpg','El nombre de la rosa','Umberto Eco','Un misterio medieval en una abadía benedictina en el siglo XIV.');
INSERT INTO books (editorial,genre,image,name,name_author,synopsis) VALUES
	 ('Salamandra','Fantasía','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243051/pgeo71g8vsayflj3tyjt.jpg','Harry Potter y la piedra filosofal','J.K. Rowling','El inicio de la saga de Harry Potter y sus aventuras en Hogwarts.'),
	 ('Debolsillo','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243064/qmkwou4ilnagsvsxa3bc.jpg','Crónica de una muerte anunciada','Gabriel García Márquez','La crónica de un asesinato anunciado en un pequeño pueblo colombiano.'),
	 ('Siruela','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243092/ogmcxmk0rkrkmz6zmrii.jpg','Pedro Páramo','Juan Rulfo','La historia de un hombre que regresa al pueblo de su madre en busca de su padre.'),
	 ('Galaxia Gutenberg','Ensayo','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243100/rk79mghffxkzczrxwhir.jpg','Sapiens','Yuval Noah Harari','Un recorrido por la historia de la humanidad desde la prehistoria hasta la era moderna.'),
	 ('Maeva','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243110/djuhinjkmrm0wayr9ir7.jpg','El alquimista','Paulo Coelho','La historia de un joven pastor andaluz en busca de su leyenda personal.'),
	 ('Blackie Books','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243121/xkznnnpnrvwg0cshee6g.jpg','El guardián entre el centeno','J.D. Salinger','Las aventuras y pensamientos de Holden Caulfield, un adolescente rebelde.'),
	 ('Destino','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243127/sjwkvi9mjzp8a6lcyuwn.jpg','La casa de los espíritus','Isabel Allende','Una saga familiar llena de magia y realismo en el Chile del siglo XX.'),
	 ('Ediciones B','Ciencia Ficción','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243133/oowadyodlg3uftzkk1iz.jpg','Fundación','Isaac Asimov','La historia de un grupo de científicos que buscan preservar el conocimiento humano.'),
	 ('Atalanta','Ensayo','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243140/ldfquclog1yqcntkogck.jpg','El hombre que confundió a su mujer con un sombrero','Oliver Sacks','Una colección de estudios de casos sobre trastornos neurológicos.'),
	 ('Alianza','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243145/zyjry0vtiyvv8rujv8di.jpg','Fahrenheit 451','Ray Bradbury','Una distopía donde los libros están prohibidos y los bomberos queman libros.');
INSERT INTO books (editorial,genre,image,name,name_author,synopsis) VALUES
	 ('Mondadori','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243151/v7crptns0xzcoze53do0.jpg','La carretera','Cormac McCarthy','La travesía de un padre y su hijo a través de un paisaje post-apocalíptico.'),
	 ('Navona','Novela','http://res.cloudinary.com/du4qwkruj/image/upload/v1717243157/jctdeut6xsk5nvwsea11.jpg','El extranjero','Albert Camus','La historia de Meursault y su indiferencia hacia la sociedad que lo rodea.');
